### ISSUE TITLE
Only show final create complete

### ISSUE THREAD

**Issue by bignellrp** [alestic/aws-cloudformation-stack-status#5]
Great work.  Thanks for this script.

Would it be possible to have an option to just show when a stack is complete and show only the outputs on the screen? I really just need to see a fail message or a complete message with outputs.

**Comment by bignellrp** [comment]
I've found there is a wait command which i have found useful but it would still be nice for a way that this script could finish when its all complete.

`aws cloudformation wait stack-create-complete --stack-name $STACK`

**Comment by ehammond** [comment]
I'd like to keep this particular script simple and clean, but you are welcome to fork and extend it.

You might be able to just run the wait command followed by a single run of aws-cloudformation-stack-status.
